// action type
export const SET_ACTIVE_REPO = 'SET_ACTIVE_REPO'
export const FETCH_REPOS_SUCCESS = 'FETCH_REPOS_SUCCESS'
export const FETCH_REPOS_REQUEST = 'FETCH_REPOS_REQUEST'
export const FETCH_REPOS_FAILURE = 'FETCH_REPOS_FAILURE'

export const FETCH_REPO_SUCCESS = 'FETCH_REPO_SUCCESS'
export const FETCH_REPO_REQUEST = 'FETCH_REPO_REQUEST'
export const FETCH_REPO_FAILURE = 'FETCH_REPO_FAILURE'

export const CLOSE_NETWORK_ALERT = 'CLOSE_NETWORK_ALERT'
